languageCode = "lt"
languageName = "Lithuanian"
weight = 1
title = "Keliauk Vienas"

[params]
  displayName = "LT"
  isoCode = "lt"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Keliauk Vienas"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Edgaras"
  links = [
    { email = "mailto:e.ausvicas+keliaukvienas@gmail.com" }
  ]